"""Every number the report quotes, collected from ``results/`` into LaTeX macros.

The report is prose, and prose cannot be re-run. Left to itself a ``.tex`` file accumulates
numbers that were true of the fits that existed when the sentence was written, and nothing
downstream ever notices when a refit moves one of them — which is the same failure mode
``scripts/utils.py`` guards the figures against, in the one place where it would be least
visible. So the report quotes **no literal number of its own**: it writes
``\\resultnum{onsetmodelsestimatedk.sseso.rac05.day}`` and this script writes what that expands
to, from the files the tier-2 rules produced.

Two consequences worth keeping:

- **A key that does not exist is a compile error**, not a blank. ``\\resultnum`` is defined in
  ``report/report.tex`` to raise a LaTeX error for an unknown key, so a renamed model or a
  deleted analysis stops the build instead of quietly printing nothing.
- **This is a tier-2 script, not a tier-3 one.** It reads posteriors and summarises them, so it
  writes to ``results/`` and the ``report`` rule (tier 3) reads only what it wrote. Restyling
  the report's prose never re-runs a fit; refitting does re-run this.

What it does *not* do is compute anything the pipeline does not already compute. Posterior
summaries come from :mod:`end_of_outbreak.posterior_comparison`, exactly as
``dispersion_posteriors.json`` does; threshold crossings come from
:meth:`~end_of_outbreak.risk_curves.RiskCurve.first_day_below`, exactly as the
markers on the figures do. The three cross-analysis quantities it forms — the crossing shift
between an onset-anchored model and its naive counterpart, the log-evidence gain from fixing
``k`` to estimating it, and the largest RAC/RAT gap — are subtractions of numbers already in
``results/``, done here so that no sentence in the report has to do arithmetic.

Keys are ``.``-separated and carry no underscores, since they are expanded through
``\\csname``: an analysis or model name is slugged by dropping everything but its letters and
digits (``onset_models_estimated_k`` → ``onsetmodelsestimatedk``, ``sse_so`` → ``sseso``).
The mapping is mechanical rather than a table, so it cannot fall out of date.
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import xarray as xr
from numpy.typing import NDArray

from end_of_outbreak import (
    configuration,
    delay_distributions,
    outbreak_data,
    pymc_models,
    risk_curves,
)
from end_of_outbreak import posterior_comparison as pc
from end_of_outbreak.model_specifications import LogNormalPrior, specification_of

RISK_COLUMN = "risk_of_additional_cases"
TRANSMISSION_RISK_COLUMN = "risk_of_additional_transmission"
STANDARD_ERROR_COLUMN = "monte_carlo_standard_error"

THRESHOLDS: tuple[float, ...] = (0.05, 0.01)
"""The two RAC levels the end-of-outbreak literature declares on, as the figures draw them."""

REPRODUCTION_NUMBERS: tuple[str, ...] = ("R_pre", "R_post")
DISPERSION = "k"

NEVER = "never"
"""What a threshold crossing renders as when the curve never settles below it in the window."""

REFERENCE_DAY = 90
"""One mid-descent day the report compares every model on.

The crossings say when each curve settles; they do not say how far apart the curves are while
they are still falling, and on this series the models are ordered differently at different
heights. Day 90 is the day §5.4 of the implementation plan works its SSE/SSI/DLO decomposition
on, so quoting the fitted curves there keeps the report's arithmetic comparable with it.
"""


# ---------------------------------------------------------------------------------------
# The macro file
# ---------------------------------------------------------------------------------------


class NumberFile:
    """Accumulates ``\\defresultnum{key}{value}`` lines, refusing to define a key twice."""

    def __init__(self) -> None:
        self._entries: dict[str, str] = {}

    def set(self, key: str, value: str) -> None:
        if key in self._entries:
            raise ValueError(f"{key!r} defined twice, with {self._entries[key]!r} and {value!r}")
        self._entries[key] = value

    def __len__(self) -> int:
        return len(self._entries)

    def render(self, *, sources: list[str]) -> str:
        """The file to write, sorted by key so a diff shows what moved."""
        provenance = "\n".join(f"%   {source}" for source in sources)
        body = "\n".join(
            f"\\defresultnum{{{key}}}{{{self._entries[key]}}}" for key in sorted(self._entries)
        )
        return (
            "% Generated by scripts/run_report_numbers.py -- do not edit.\n"
            "%\n"
            "% Every number report/report.tex quotes, keyed for \\resultnum. Read from:\n"
            f"{provenance}\n"
            "%\n"
            f"% {len(self._entries)} entries.\n"
            f"{body}\n"
        )


def slug(name: str) -> str:
    """An analysis or model name as it appears in a key: letters and digits only."""
    return re.sub(r"[^a-z0-9]", "", name.lower())


def repository_path(path: Path) -> str:
    """``path`` relative to the repository root where it is inside it, so the header commits well.

    The generated file is committed, so an absolute path in it would differ between machines and
    show up as a spurious diff on every regeneration.
    """
    resolved = Path(path).resolve()
    try:
        return str(resolved.relative_to(configuration.REPO_ROOT))
    except ValueError:
        return str(resolved)


# --- formatting ------------------------------------------------------------------------
#
# Rounding is a presentation decision and so it belongs here rather than in the report, where
# the same quantity could end up quoted to three decimal places in one section and two in
# another. One helper per kind of quantity, used everywhere that quantity appears.


def fixed(value: float, decimals: int) -> str:
    return f"{value:.{decimals}f}"


def trimmed(value: float, decimals: int) -> str:
    """``fixed``, with trailing zeros dropped: 11.40 becomes 11.4 and 4.57 stays 4.57.

    Used for the delay distributions, which are quoted in running prose as ``a mean of 11.4
    days`` rather than in a column of a table. A fixed number of decimals would either write
    ``11.40`` there or lose the second digit of the TOST standard deviation.
    """
    return fixed(value, decimals).rstrip("0").rstrip(".")


def interval(summary: pc.PosteriorSummary, decimals: int) -> str:
    """``median (lower--upper)``, the form the figures' legends use."""
    return (
        f"{summary.median:.{decimals}f} "
        f"({summary.interval_lower:.{decimals}f}--{summary.interval_upper:.{decimals}f})"
    )


def date_text(date: datetime.date) -> str:
    """``5 April 2018`` — no leading zero, since these are read as prose."""
    return f"{date.day} {date:%B} {date.year}"


def small_probability(probability: float) -> str:
    """A posterior model probability, rendered so that "essentially zero" stays readable.

    Matches :func:`scripts.utils._probability_text`, which labels the same numbers on the pie:
    the report and the panel must not disagree about how small "small" is.
    """
    if probability >= 0.01:
        return f"{probability:.2f}"
    if probability == 0.0:
        return "\\ensuremath{<10^{-300}}"
    exponent = int(np.floor(np.log10(probability)))
    mantissa = probability / 10.0**exponent
    return f"\\ensuremath{{{mantissa:.0f}\\times 10^{{{exponent}}}}}"


def signed(value: float, decimals: int) -> str:
    """A difference, with its sign always shown; ``+0`` and ``-0`` are both written ``0``."""
    rounded = round(value, decimals)
    if rounded == 0:
        return math_mode(f"{0:.{decimals}f}")
    return math_mode(f"{rounded:+.{decimals}f}")


def math_mode(text: str) -> str:
    """Wrap a value that carries a sign, so that TeX sets a minus rather than a hyphen.

    A bare ``-97.1`` in running text renders as a hyphen, which is visibly too short and reads
    as a dash. Every quantity that can be negative goes through here.
    """
    return f"\\ensuremath{{{text}}}"


# ---------------------------------------------------------------------------------------
# Reading what the tier-2 rules wrote
# ---------------------------------------------------------------------------------------


def read_json(path: Path) -> dict[str, Any]:
    """Load a tier-2 summary, failing loudly rather than letting the report print a blank."""
    if not path.exists():
        raise FileNotFoundError(
            f"no results file at {path}. The report quotes numbers from it and there is "
            "deliberately no fallback — run the pipeline (`pixi run pipeline`) first."
        )
    with open(path) as handle:
        return json.load(handle)


def read_risk_curve(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"no RAC curve at {path}; run the `rac` rule that writes it")
    frame = pd.read_csv(path)
    frame["date"] = pd.to_datetime(frame["date"])
    return frame


def read_diagnostics(path: Path) -> pd.DataFrame:
    """One model's per-conditioning-day sampler diagnostics."""
    if not path.exists():
        raise FileNotFoundError(
            f"no sampler diagnostics at {path}; the `rac` rule writes them beside the curve"
        )
    return pd.read_csv(path)


def open_posterior(path: Path) -> xr.DataTree:
    """One fit's draws.

    Opened with xarray directly rather than through :mod:`end_of_outbreak.fitting`, for the
    reason ``scripts/utils.py`` gives: a fit is an ``xarray.DataTree`` and nothing here needs
    the model-building machinery that importing ``fitting`` would pull in.
    """
    if not path.exists():
        raise FileNotFoundError(f"no fit at {path}; run the `fit` rule that writes it")
    return xr.open_datatree(str(path), engine="h5netcdf").load()


def draws_of(posterior: xr.DataTree, name: str) -> NDArray[np.float64]:
    """One scalar parameter's draws, chains flattened."""
    return np.asarray(posterior.posterior.data_vars[name]).reshape(-1)


# ---------------------------------------------------------------------------------------
# The sections of the file
# ---------------------------------------------------------------------------------------


def add_setting(numbers: NumberFile, data: outbreak_data.OutbreakData) -> None:
    """The outbreak itself: totals, key dates and the analysis window."""
    onsets = data.onsets
    last_onset_day = int(np.flatnonzero(onsets > 0)[-1])
    numbers.set("data.totalcases", str(data.total_cases))
    numbers.set("data.days", str(data.n_days))
    numbers.set("data.preertcases", str(int(onsets[data.pre_ert_mask].sum())))
    numbers.set("data.postertcases", str(int(onsets[data.post_ert_mask].sum())))
    numbers.set("data.onsetdays", str(int((onsets > 0).sum())))
    numbers.set("data.maxdailyonsets", str(int(onsets.max())))
    numbers.set("data.firstday", "0")
    numbers.set("data.firstdate", date_text(data.date_of(0)))
    numbers.set("data.ertarrivalday", str(data.ert_arrival_day))
    numbers.set("data.ertarrivaldate", date_text(data.date_of(data.ert_arrival_day)))
    numbers.set("data.lastonsetday", str(last_onset_day))
    numbers.set("data.lastonsetdate", date_text(data.date_of(last_onset_day)))
    numbers.set("data.withdrawalday", str(data.ert_withdrawal_day))
    numbers.set("data.withdrawaldate", date_text(data.date_of(data.ert_withdrawal_day)))
    numbers.set("data.referenceday", str(REFERENCE_DAY))
    numbers.set("data.referencedate", date_text(data.date_of(REFERENCE_DAY)))


def add_delays(numbers: NumberFile, config: dict[str, Any]) -> None:
    """The delay triple, and the variance budget that admits it.

    Rebuilt from the config rather than quoted from it, so that the residual TOST and the
    fidelity of the decomposition are the ones the models were actually driven by.
    """
    shared = config["shared"]
    delays = configuration.onset_anchored_delays_from_config(config)
    alternative = configuration.gamma_delay_from_config(shared["serial_interval_outbreak_specific"])
    for prefix, delay in (
        ("delays.serialinterval", configuration.gamma_delay_from_config(shared["serial_interval"])),
        ("delays.incubation", delays.incubation_delay),
        ("delays.tost", delays.tost_delay),
        ("delays.alternativeserialinterval", alternative),
    ):
        numbers.set(f"{prefix}.mean", trimmed(delay.mean, 2))
        numbers.set(f"{prefix}.sd", trimmed(delay.sd, 2))
        numbers.set(f"{prefix}.variance", trimmed(delay.variance, 2))
    numbers.set("delays.maxlag", str(int(shared["max_lag"])))
    numbers.set("delays.discrepancy", f"{delays.serial_interval_discrepancy():.5f}")
    numbers.set("delays.tolerance", fixed(float(shared["serial_interval_tolerance"]), 2))


def add_priors(numbers: NumberFile, config: dict[str, Any], analyses: list[str]) -> None:
    """The shared priors. Identical across models by design (§6.2), so defined once."""
    priors = config["shared"]["priors"]
    R_prior = LogNormalPrior.from_config(priors["R_pre"])
    numbers.set("priors.R.median", fixed(R_prior.median, 1))
    numbers.set("priors.R.quantilelower", fixed(float(R_prior.frozen().ppf(0.025)), 1))
    numbers.set("priors.R.quantileupper", fixed(float(R_prior.frozen().ppf(0.975)), 1))

    k_blocks = [
        config["analyses"][analysis]["k_prior"]
        for analysis in analyses
        if config["analyses"][analysis].get("fixed_k") is None
    ]
    if k_blocks:
        k_prior = LogNormalPrior.from_config(k_blocks[0])
        numbers.set("priors.k.median", fixed(k_prior.median, 2))
        numbers.set("priors.k.quantilelower", fixed(float(k_prior.frozen().ppf(0.025)), 2))
        numbers.set("priors.k.quantileupper", fixed(float(k_prior.frozen().ppf(0.975)), 2))


def add_sampler(numbers: NumberFile, block: dict[str, Any], prefix: str) -> None:
    """What the sampler was asked for, so the methods can state it per analysis."""
    sampler = block["sampler"]
    numbers.set(f"{prefix}.draws", str(int(sampler["draws"])))
    numbers.set(f"{prefix}.tune", str(int(sampler["tune"])))
    numbers.set(f"{prefix}.chains", str(int(sampler["chains"])))
    numbers.set(f"{prefix}.targetaccept", fixed(float(sampler["target_accept"]), 2))
    fixed_k = block.get("fixed_k")
    numbers.set(f"{prefix}.fixedk", "estimated" if fixed_k is None else fixed(float(fixed_k), 2))
    # The number of models is the denominator of the uniform prior over models (§6.2), which the
    # posterior model probabilities are not interpretable without.
    numbers.set(f"{prefix}.nmodels", str(len(block["models"])))


def add_parameters(numbers: NumberFile, posterior: xr.DataTree, prefix: str) -> None:
    """Posterior medians and 95% credible intervals for the scalars the report compares.

    Summarised with the same function ``dispersion_posteriors.json`` uses, so the ``k`` line the
    report quotes and the one the figure's legend carries are the same computation.
    """
    for name in (*REPRODUCTION_NUMBERS, DISPERSION):
        if name not in posterior.posterior.data_vars:
            continue  # k is a constant in the graph where the analysis fixed it.
        summary = pc.summarise_posterior(draws_of(posterior, name))
        decimals = 3 if name == DISPERSION else 2
        key = f"{prefix}.{slug(name)}"
        numbers.set(f"{key}.median", fixed(summary.median, decimals))
        numbers.set(f"{key}.lower", fixed(summary.interval_lower, decimals))
        numbers.set(f"{key}.upper", fixed(summary.interval_upper, decimals))
        numbers.set(f"{key}.interval", interval(summary, decimals))


def add_latent_block(
    numbers: NumberFile,
    posterior: xr.DataTree,
    model: str,
    data: outbreak_data.OutbreakData,
    delays: delay_distributions.OnsetAnchoredDelays,
    prefix: str,
) -> None:
    """How many latents the model carries, and how many survived exact marginalisation.

    The total comes from the block layout the builders use; the sampled count is the width of
    the block in the draws. The difference is what the conjugate marginalisation removed, which
    is the methods claim this pins.
    """
    specification = specification_of(model)
    if specification.latent_variable is None:
        return
    structure = pymc_models.latent_block_structure(
        model, data.onsets, delays=delays, switch_day=data.ert_arrival_day
    )
    sampled = int(posterior.posterior.sizes[structure.dimension])
    numbers.set(f"{prefix}.latents.total", str(int(structure.days.size)))
    numbers.set(f"{prefix}.latents.sampled", str(sampled))
    numbers.set(f"{prefix}.latents.marginalised", str(int(structure.days.size) - sampled))


def add_risk_curve(
    numbers: NumberFile,
    frame: pd.DataFrame,
    data: outbreak_data.OutbreakData,
    prefix: str,
    *,
    reference_day: int = REFERENCE_DAY,
) -> None:
    """Threshold crossings, the risk left on the withdrawal day, and the Monte-Carlo error.

    RAT is written only by the onset-anchored RAC tier, so its keys appear only for those
    models — which is the asymmetry the supplementary figure is about.
    """
    if reference_day not in set(np.asarray(frame["day"], dtype=np.int64).tolist()):
        raise ValueError(
            f"the reference day {reference_day} is not in this curve, which runs from "
            f"{int(frame['day'].min())} to {int(frame['day'].max())}. It is the one day the "
            "report compares every model on, so it has to be inside the analysis window."
        )
    columns = [(RISK_COLUMN, "rac", STANDARD_ERROR_COLUMN)]
    if TRANSMISSION_RISK_COLUMN in frame:
        columns.append((TRANSMISSION_RISK_COLUMN, "rat", "transmission_monte_carlo_standard_error"))
    days = np.asarray(frame["day"], dtype=np.int64)
    # Two Monte-Carlo error summaries, because the honest maximum and the useful one differ. The
    # error is largest while the curve is near 1 and every draw is contributing, which is a
    # region no comparison is made in; the decision-relevant figure is the largest error over the
    # case-free tail, where the thresholds are crossed and two curves are read against each other.
    late = days >= int(np.flatnonzero(np.asarray(data.onsets) > 0)[-1])
    for column, name, error_column in columns:
        curve = risk_curves.RiskCurve(
            days=days, risk=np.asarray(frame[column], dtype=np.float64), n_draws=0
        )
        for threshold in THRESHOLDS:
            day = curve.first_day_below(threshold)
            key = f"{prefix}.{name}{round(threshold * 100):02d}"
            numbers.set(f"{key}.day", NEVER if day is None else str(day))
            numbers.set(f"{key}.date", NEVER if day is None else date_text(data.date_of(day)))
        numbers.set(f"{prefix}.{name}.final", fixed(float(curve.risk[-1]), 3))
        numbers.set(
            f"{prefix}.{name}.reference",
            fixed(float(curve.risk[days == reference_day][0]), 3),
        )
        numbers.set(f"{prefix}.{name}.mcse", f"{float(frame[error_column].max()):.4f}")
        numbers.set(
            f"{prefix}.{name}.mcselate", f"{float(frame.loc[late, error_column].max()):.4f}"
        )

    if TRANSMISSION_RISK_COLUMN in frame:
        gap = np.asarray(frame[RISK_COLUMN] - frame[TRANSMISSION_RISK_COLUMN], dtype=np.float64)
        widest = int(np.argmax(gap))
        numbers.set(f"{prefix}.gap.max", fixed(float(gap[widest]), 3))
        numbers.set(f"{prefix}.gap.day", str(int(days[widest])))
        numbers.set(f"{prefix}.gap.date", date_text(data.date_of(int(days[widest]))))
        # How long the pipeline holds a case-based declaration back after transmission risk has
        # already settled: the same threshold, read off the two curves, differenced here so the
        # report states it rather than working it out.
        for threshold in THRESHOLDS:
            label = f"{round(threshold * 100):02d}"
            crossings = [
                risk_curves.RiskCurve(
                    days=days, risk=np.asarray(frame[column], dtype=np.float64), n_draws=0
                ).first_day_below(threshold)
                for column in (RISK_COLUMN, TRANSMISSION_RISK_COLUMN)
            ]
            case_day, transmission_day = crossings
            numbers.set(
                f"{prefix}.gap.shift{label}",
                NEVER
                if case_day is None or transmission_day is None
                else str(case_day - transmission_day),
            )


def add_evidence(numbers: NumberFile, evidence: dict[str, Any], analysis: str) -> None:
    """Log marginal likelihoods and the posterior model probabilities they imply."""
    prefix = slug(analysis)
    for model in evidence["models"]:
        key = f"{prefix}.{slug(model)}"
        numbers.set(
            f"{key}.logevidence", math_mode(fixed(float(evidence["log_evidence"][model]), 1))
        )
        numbers.set(
            f"{key}.logevidencese",
            f"{float(evidence['log_evidence_standard_error'][model]):.3f}",
        )
        numbers.set(
            f"{key}.probability",
            small_probability(float(evidence["posterior_model_probability"][model])),
        )


def add_dispersion(numbers: NumberFile, dispersion: dict[str, Any], analysis: str) -> None:
    """Every pairwise divergence between the ``k`` posteriors, as the file records them."""
    prefix = slug(analysis)
    for pair, divergence in dispersion["divergence"].items():
        first, second = pair.split("_vs_")
        key = f"{prefix}.{slug(first)}-vs-{slug(second)}"
        numbers.set(f"{key}.medianratio", fixed(float(divergence["median_ratio"]), 2))
        numbers.set(f"{key}.overlap", fixed(float(divergence["overlap"]), 3))
        numbers.set(f"{key}.probabilitygreater", fixed(float(divergence["probability_greater"]), 3))


@dataclass(frozen=True)
class Diagnostics:
    """The worst convergence figures over a set of fits.

    The worst case is the only summary worth quoting: "every fit converged" is a claim about the
    maximum ``R̂`` and the minimum effective sample size, not about their averages. Aggregating
    the same way twice — per analysis and over all of them — is what lets the report make the
    global claim from a global number rather than from one analysis's.

    The set is every fit behind every curve, not just the fits to the complete record: the
    estimand conditions on the record through each day, so each curve rests on one fit per
    conditioning day and a claim that leaves them out would cover a small fraction of the study.
    """

    fits: int
    max_rhat: float
    min_bulk_ess: float
    divergences: int

    def merged_with(self, other: Diagnostics) -> Diagnostics:
        return Diagnostics(
            fits=self.fits + other.fits,
            max_rhat=max(self.max_rhat, other.max_rhat),
            min_bulk_ess=min(self.min_bulk_ess, other.min_bulk_ess),
            divergences=self.divergences + other.divergences,
        )


def measure_diagnostics(tables: dict[str, pd.DataFrame]) -> Diagnostics:
    """Convergence over every conditioning-day fit of every model in one analysis.

    Read from the per-day tables the ``rac`` step writes rather than recomputed, so the numbers
    the report quotes are the ones the pipeline's own acceptance gate applied. Those cover every
    sampled variable, latent block included — which is a stronger claim than the reported
    scalars alone, and the one the gate enforces.
    """
    return Diagnostics(
        fits=sum(len(table) for table in tables.values()),
        max_rhat=max(float(table["max_r_hat"].max()) for table in tables.values()),
        min_bulk_ess=min(float(table["min_ess_bulk"].min()) for table in tables.values()),
        divergences=sum(int(table["divergences"].sum()) for table in tables.values()),
    )


def add_diagnostics(numbers: NumberFile, diagnostics: Diagnostics, prefix: str) -> None:
    """Write one set of convergence figures under ``<prefix>.diagnostics``."""
    numbers.set(f"{prefix}.diagnostics.fits", str(diagnostics.fits))
    # Three decimals, not two: the acceptance gate is at 1.01, and "1.00" would not let a reader
    # tell a comfortable pass from a marginal one.
    numbers.set(f"{prefix}.diagnostics.maxrhat", fixed(diagnostics.max_rhat, 3))
    numbers.set(f"{prefix}.diagnostics.minbulkess", str(int(np.floor(diagnostics.min_bulk_ess))))
    numbers.set(f"{prefix}.diagnostics.divergences", str(diagnostics.divergences))


# --- the cross-analysis subtractions -----------------------------------------------------


def add_onset_shifts(numbers: NumberFile, analysis: str, curves: dict[str, pd.DataFrame]) -> None:
    """How far onset anchoring moves each threshold crossing, in days.

    The headline of Stage 9, and a subtraction rather than a new quantity: it pairs each
    onset-anchored model with the naive model of the same mechanism, which is the only
    comparison in the analysis that holds the mechanism fixed and varies the anchoring.
    """
    prefix = slug(analysis)
    for onset_model, naive_model in (("sse_so", "sse"), ("ssi_so", "ssi")):
        if onset_model not in curves or naive_model not in curves:
            continue
        key = f"{prefix}.{slug(onset_model)}-vs-{slug(naive_model)}"
        for threshold in THRESHOLDS:
            onset_day, naive_day = (
                _crossing(curves[model], threshold) for model in (onset_model, naive_model)
            )
            name = f"{key}.shift{round(threshold * 100):02d}"
            if onset_day is None or naive_day is None:
                numbers.set(name, NEVER)
            else:
                numbers.set(name, str(naive_day - onset_day))


def _crossing(frame: pd.DataFrame, threshold: float) -> int | None:
    curve = risk_curves.RiskCurve(
        days=np.asarray(frame["day"], dtype=np.int64),
        risk=np.asarray(frame[RISK_COLUMN], dtype=np.float64),
        n_draws=0,
    )
    return curve.first_day_below(threshold)


def add_evidence_gains(
    numbers: NumberFile, results_root: Path, analyses: list[str], config: dict[str, Any]
) -> None:
    """What letting ``k`` move is worth, in nats, for each model that is fitted both ways.

    Analysis 2 against Analysis 1 and Analysis 4 against Analysis 3: the same models, the same
    data, the same priors on ``R``, differing only in whether ``k`` is held at the literature
    value. A large gain says the literature value was not this model's.
    """
    for analysis in analyses:
        if config["analyses"][analysis].get("fixed_k") is not None:
            continue
        counterpart = analysis.replace("estimated_k", "fixed_k")
        if counterpart == analysis or counterpart not in analyses:
            continue
        estimated = read_json(results_root / analysis / "model_evidence.json")["log_evidence"]
        held = read_json(results_root / counterpart / "model_evidence.json")["log_evidence"]
        for model in estimated:
            if model in held:
                gain = float(estimated[model]) - float(held[model])
                # Two decimals rather than one: the gains span 7.4 nats down to hundredths, and
                # the small ones are the interesting end — a model whose evidence does not move
                # when `k` is released is one the literature value already fitted.
                numbers.set(f"{slug(analysis)}.{slug(model)}.evidencegain", signed(gain, 2))


# ---------------------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------------------


def collect(
    *, analyses: list[str], config: dict[str, Any], data_path: Path, results_root: Path
) -> tuple[NumberFile, list[str]]:
    """Every macro the report can use, and the files they came from."""
    numbers = NumberFile()
    data = outbreak_data.load_onset_data(data_path)
    delays = configuration.onset_anchored_delays_from_config(config)
    sources = [repository_path(data_path)]

    add_setting(numbers, data)
    add_delays(numbers, config)
    add_priors(numbers, config, analyses)
    overall: Diagnostics | None = None

    for analysis in analyses:
        block = configuration.analysis_config(config, analysis)
        models = list(block["models"])
        directory = results_root / analysis
        add_sampler(numbers, block, slug(analysis))

        posteriors = {
            model: open_posterior(directory / f"{model}_posterior.nc") for model in models
        }
        curves = {model: read_risk_curve(directory / f"{model}_rac.csv") for model in models}
        for model in models:
            prefix = f"{slug(analysis)}.{slug(model)}"
            add_parameters(numbers, posteriors[model], prefix)
            add_latent_block(numbers, posteriors[model], model, data, delays, prefix)
            add_risk_curve(numbers, curves[model], data, prefix)
        diagnostics = measure_diagnostics(
            {
                model: read_diagnostics(directory / f"{model}_rac_diagnostics.csv")
                for model in models
            }
        )
        add_diagnostics(numbers, diagnostics, slug(analysis))
        overall = diagnostics if overall is None else overall.merged_with(diagnostics)
        add_onset_shifts(numbers, analysis, curves)

        add_evidence(numbers, read_json(directory / "model_evidence.json"), analysis)
        if block.get("fixed_k") is None:
            add_dispersion(
                numbers,
                read_json(directory / "dispersion_posteriors.json"),
                analysis,
            )
        sources.extend(sorted(repository_path(path) for path in _analysis_files(directory, models)))

    # The report makes one claim about every fit in the study ("no divergences anywhere"), so it
    # gets a number aggregated the same way, rather than quoting one analysis's and hoping.
    if overall is not None:
        add_diagnostics(numbers, overall, "overall")
    add_evidence_gains(numbers, results_root, analyses, config)
    return numbers, sources


def _analysis_files(directory: Path, models: list[str]) -> Iterator[Path]:
    for model in models:
        yield directory / f"{model}_posterior.nc"
        yield directory / f"{model}_rac.csv"
        yield directory / f"{model}_rac_diagnostics.csv"
    yield directory / "model_evidence.json"
    dispersion = directory / "dispersion_posteriors.json"
    if dispersion.exists():
        yield dispersion


def main(argv: list[str] | None = None) -> None:
    args = parse_arguments(argv)
    numbers, sources = collect(
        analyses=args.analyses,
        config=configuration.load_config(args.config),
        data_path=args.data,
        results_root=args.results_root,
    )
    output = configuration.ensure_parent(args.output)
    output.write_text(numbers.render(sources=sources))
    print(f"wrote {len(numbers)} numbers to {output}")


def parse_arguments(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=configuration.DEFAULT_CONFIG_FILE)
    parser.add_argument("--data", type=Path, default=outbreak_data.DEFAULT_DATA_FILE)
    parser.add_argument("--results-root", type=Path, default=configuration.REPO_ROOT / "results")
    parser.add_argument(
        "--analyses",
        nargs="+",
        required=True,
        help="the analyses to collect, in report order; the Snakefile passes IMPLEMENTED_ANALYSES",
    )
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args(argv)


if __name__ == "__main__":
    main()
