"""Particle-filter and PMMH checks for the onset-anchored models.

Writes three auditable tables and a short interpretation to ``validation/results``:

- filter likelihood variability on the real record (the PMMH feasibility rule);
- RAC from PyMC against the particle smoother at matched conditioning, with the filtering
  curve beside it;
- PMMH against PyMC on histories generated by the onset simulators.

The matched comparison conditions both sides on the whole record, which is what makes it a check
of the *arithmetic* — and, since the PyMC side integrates the latents the fit removed out of the
risk in closed form rather than drawing them, of that marginalisation too. The filtering curve
comes from :mod:`end_of_outbreak.filtered_risk`, the module the pipeline would use under
``rac.method: single_fit_filtered``, so it exercises a results path rather than a reimplementation
of one.

This script is intentionally absent from the Snakefile: it validates the implementation and
feeds no report figure.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from end_of_outbreak import (
    configuration,
    delay_distributions,
    filtered_risk,
    fitting,
    forward_simulation,
    outbreak_data,
    particle_filter,
    particle_mcmc,
)
from end_of_outbreak import risk_of_additional_cases as rac
from end_of_outbreak.delay_distributions import OnsetAnchoredDelays
from end_of_outbreak.model_specifications import LogNormalPrior, TransmissionParameters

OUTPUT_DIRECTORY = configuration.REPO_ROOT / "validation" / "results"
SYNTHETIC_OUTPUT = OUTPUT_DIRECTORY / "onset_particle_mcmc_synthetic.csv"
VARIANCE_OUTPUT = OUTPUT_DIRECTORY / "onset_smc_variance.csv"
RAC_OUTPUT = OUTPUT_DIRECTORY / "onset_rac_filtering.csv"
SUMMARY_OUTPUT = OUTPUT_DIRECTORY / "onset_particle_mcmc_validation.md"


def _prior(median: float) -> LogNormalPrior:
    return LogNormalPrior.from_median_and_quantile(
        median=median, quantile=median / 4.0, probability=0.025
    )


def measure_variance(
    counts: np.ndarray,
    delays: OnsetAnchoredDelays,
    *,
    switch_day: int,
    repeats: int,
    seed: int,
) -> pd.DataFrame:
    """Real-record ``Var(log L_hat)`` at plausible onset-model parameters."""
    rows: list[dict[str, Any]] = []
    parameters = TransmissionParameters(R_pre=1.85, R_post=0.27, k=0.18)
    for model_index, model in enumerate(("sse_so", "ssi_so")):
        for n_particles in (250, 1000):
            result = particle_mcmc.estimate_log_evidence_variance(
                model,
                counts,
                parameters,
                delays=delays,
                switch_day=switch_day,
                n_particles=n_particles,
                repeats=repeats,
                rng=np.random.default_rng([seed, model_index, n_particles]),
            )
            rows.append(
                {
                    "model": model,
                    "n_particles": n_particles,
                    "n_repeats": repeats,
                    "mean_log_evidence": result.mean,
                    "sd_log_evidence": np.sqrt(result.variance),
                    "var_log_evidence": result.variance,
                }
            )
    return pd.DataFrame(rows)


def matched_rac_check(
    counts: np.ndarray,
    delays: OnsetAnchoredDelays,
    *,
    switch_day: int,
    n_particles: int,
    seed: int,
) -> pd.DataFrame:
    """MCMC-smoothed vs particle-smoothed RAC, and filtering minus smoothing."""
    parameters = TransmissionParameters(R_pre=1.85, R_post=0.27, k=0.18)
    rows = []
    for model_index, model in enumerate(("sse_so", "ssi_so")):
        filtered = particle_filter.filter_onset_anchored(
            model,
            counts,
            parameters,
            delays=delays,
            switch_day=switch_day,
            n_particles=n_particles,
            rng=np.random.default_rng([seed, model_index, 0]),
        )
        assert filtered.latent_paths is not None
        particle_probabilities = rac.onset_event_probabilities(
            model,
            counts=counts,
            delays=delays,
            switch_day=switch_day,
            R_pre=np.full(n_particles, parameters.R_pre),
            R_post=np.full(n_particles, parameters.R_post),
            k=np.full(n_particles, parameters.k),
            latent=filtered.latent_paths,
        )
        particle_smoothed = particle_probabilities.risk_of_additional_cases().risk

        fitted = fitting.fit_model(
            model,
            counts,
            delays=delays,
            switch_day=switch_day,
            R_pre=parameters.R_pre,
            R_post=parameters.R_post,
            k=parameters.k,
            latent_parameterisation="marginalised_inverse_cdf",
            sampler=fitting.SamplerSettings(
                draws=1000, tune=1000, chains=2, seed=seed + model_index
            ),
        )
        state = rac.posterior_state(
            model,
            fitted,
            counts,
            delays=delays,
            switch_day=switch_day,
            latent_parameterisation="marginalised_inverse_cdf",
            fixed_R_pre=parameters.R_pre,
            fixed_R_post=parameters.R_post,
            fixed_k=parameters.k,
        )
        assert state.sampled_infectivity is not None
        mcmc_smoothed = (
            rac.risk_log_probabilities(
                model, state, counts=counts, delays=delays, switch_day=switch_day
            )
            .risk_of_additional_cases()
            .risk
        )

        # The filtering estimator, exercised through the module the pipeline would use rather
        # than re-derived here. At fixed θ a one-draw posterior state is all it needs, and the
        # result is directly comparable with the MCMC curve only in the sense that both are
        # conditional on the same parameters — the states differ, which is the point.
        filtering = (
            filtered_risk.risk_by_filtering(
                model,
                rac.PosteriorState(
                    R_pre=np.array([parameters.R_pre]),
                    R_post=np.array([parameters.R_post]),
                    k=np.array([parameters.k]),
                    sampled_infectivity=None,
                ),
                counts=counts,
                delays=delays,
                switch_day=switch_day,
                n_particles=n_particles,
                rng=np.random.default_rng([seed, model_index, 1]),
            )
            .estimate.risk_of_additional_cases()
            .risk
        )
        for day in range(counts.size):
            rows.append(
                {
                    "model": model,
                    "day": day,
                    "mcmc_smoothed_rac": mcmc_smoothed[day],
                    "particle_smoothed_rac": particle_smoothed[day],
                    "particle_filtering_rac": filtering[day],
                }
            )
    return pd.DataFrame(rows)


def synthetic_posterior_check(
    delays: OnsetAnchoredDelays, *, switch_day: int, seed: int
) -> pd.DataFrame:
    """PMMH and PyMC posteriors on histories generated by each onset model."""
    truth = TransmissionParameters(R_pre=1.8, R_post=0.65, k=0.45)
    R_pre_prior, R_post_prior, k_prior = _prior(1.0), _prior(1.0), _prior(0.45)
    rows: list[dict[str, Any]] = []
    for model_index, model in enumerate(("sse_so", "ssi_so")):
        simulation = forward_simulation.simulate_onset_anchored_convenient(
            model,
            truth,
            delays=delays,
            n_days=18,
            switch_day=switch_day,
            n_replicates=1,
            rng=np.random.default_rng((10, 5)[model_index]),
        )
        counts = simulation.onsets[0]
        fitted = fitting.fit_model(
            model,
            counts,
            delays=delays,
            switch_day=switch_day,
            R_pre=R_pre_prior,
            R_post=R_post_prior,
            k=k_prior,
            latent_parameterisation="marginalised_inverse_cdf",
            sampler=fitting.SamplerSettings(
                draws=1000, tune=1000, chains=2, target_accept=0.95, seed=seed + model_index
            ),
        )
        pmmh = particle_mcmc.sample(
            model,
            counts,
            delays=delays,
            switch_day=switch_day,
            R_pre_prior=R_pre_prior,
            R_post_prior=R_post_prior,
            k=k_prior,
            n_particles=300,
            draws=4000,
            tune=1500,
            proposal_scale=np.array([0.12, 0.12, 0.1]),
            initial_parameters=truth,
            rng=np.random.default_rng([seed, model_index, 2]),
        )
        for name, pmmh_values in (
            ("R_pre", pmmh.R_pre),
            ("R_post", pmmh.R_post),
            ("k", pmmh.k),
        ):
            assert pmmh_values is not None
            pymc_values = np.asarray(fitted.posterior[name]).reshape(-1)
            pymc_interval = np.quantile(pymc_values, [0.025, 0.975])
            pmmh_interval = np.quantile(pmmh_values, [0.025, 0.975])
            rows.append(
                {
                    "model": model,
                    "parameter": name,
                    "true_value": getattr(truth, name),
                    "pymc_median": np.median(pymc_values),
                    "pymc_lower": pymc_interval[0],
                    "pymc_upper": pymc_interval[1],
                    "pmmh_median": np.median(pmmh_values),
                    "pmmh_lower": pmmh_interval[0],
                    "pmmh_upper": pmmh_interval[1],
                    "pmmh_acceptance_rate": pmmh.acceptance_rate,
                    "synthetic_cases": int(counts.sum()),
                }
            )
    return pd.DataFrame(rows)


def write_summary(variance: pd.DataFrame, curves: pd.DataFrame, synthetic: pd.DataFrame) -> None:
    """Write the conclusions beside the numerical runs."""
    variance_max = float(variance["var_log_evidence"].max())
    differences = curves.assign(
        smooth_difference=lambda x: x.particle_smoothed_rac - x.mcmc_smoothed_rac,
        filtering_difference=lambda x: x.particle_filtering_rac - x.mcmc_smoothed_rac,
    )
    worst_smooth = float(differences["smooth_difference"].abs().max())
    interval_overlap = np.minimum(synthetic.pymc_upper, synthetic.pmmh_upper) - np.maximum(
        synthetic.pymc_lower, synthetic.pmmh_lower
    )
    worst_filtering = float(differences["filtering_difference"].abs().max())
    summary = f"""# Onset-anchored particle-filter and PMMH validation

## Outcome

- The onset-filter PMMH tuning criterion is comfortably met: the largest measured
  `Var(log L_hat)` is **{variance_max:.3f}**, below the practical 1–3 range.
- With conditioning matched — both sides conditioned on the whole record — particle-smoothed and
  MCMC RAC differ by at most **{worst_smooth:.4f}**. That is the check on the arithmetic, and it
  now also checks the exact latent marginalisation: the MCMC side integrates the latents the fit
  removed out of the risk in closed form rather than drawing them.
- The filtering column is produced by `end_of_outbreak.filtered_risk`, the module the pipeline
  would use under `rac.method: single_fit_filtered`, rather than re-derived here. It differs from
  the matched smoothing curve by up to **{worst_filtering:.4f}** — a difference of *estimand*,
  not of implementation, and the same one `rac_method_comparison.csv` measures against the
  refitting estimand.
- PMMH and PyMC 95% intervals overlap for **{int((interval_overlap > 0).sum())} of
  {interval_overlap.size}** synthetic-model parameter comparisons. PMMH acceptance rates are
  {synthetic.pmmh_acceptance_rate.min():.2f}–{synthetic.pmmh_acceptance_rate.max():.2f}.

## Files

- `{VARIANCE_OUTPUT.name}` — repeated real-record SMC likelihood estimates.
- `{RAC_OUTPUT.name}` — matched smoothing equality check, and the filtering curve beside it.
- `{SYNTHETIC_OUTPUT.name}` — independent PMMH/PyMC posterior comparison on simulator output.

The main analyses remain PyMC-based. These runs validate the independent particle route and do
not feed `results/`, figures, or the Snakefile.
"""
    SUMMARY_OUTPUT.write_text(summary)


def main(argv: list[str] | None = None) -> None:
    args = parse_arguments(argv)
    config = configuration.load_config(args.config)
    # Days 0-110, the window these checks were run and committed on. The pipeline's window
    # now runs to 13 August; nothing here tests the extra case-free days, and pinning the end
    # keeps the committed outputs reproducible.
    data = outbreak_data.load_onset_data(args.data, end_date=outbreak_data.ERT_WITHDRAWAL_DATE)
    delays = configuration.onset_anchored_delays_from_config(config)
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    variance = measure_variance(
        data.onsets,
        delays,
        switch_day=data.ert_arrival_day,
        repeats=args.repeats,
        seed=args.seed,
    )
    curves = matched_rac_check(
        data.onsets,
        delays,
        switch_day=data.ert_arrival_day,
        n_particles=args.particles,
        seed=args.seed,
    )
    short_delays = delay_distributions.build_onset_anchored_delays(
        serial_interval=delay_distributions.GammaDelay(mean=3.0, sd=2.0),
        incubation=delay_distributions.GammaDelay(mean=1.5, sd=1.0),
        max_lag=18,
        tolerance=None,
    )
    synthetic = synthetic_posterior_check(short_delays, switch_day=8, seed=args.seed)
    variance.to_csv(VARIANCE_OUTPUT, index=False)
    curves.to_csv(RAC_OUTPUT, index=False)
    synthetic.to_csv(SYNTHETIC_OUTPUT, index=False)
    write_summary(variance, curves, synthetic)
    print(f"wrote {SUMMARY_OUTPUT} and three CSV files")


def parse_arguments(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=configuration.DEFAULT_CONFIG_FILE)
    parser.add_argument("--data", type=Path, default=outbreak_data.DEFAULT_DATA_FILE)
    parser.add_argument("--particles", type=int, default=10_000)
    parser.add_argument("--repeats", type=int, default=12)
    parser.add_argument("--seed", type=int, default=20260809)
    return parser.parse_args(argv)


if __name__ == "__main__":
    main()
